### ISSUE TITLE
"No module named numpy" on Blender 2.8 in ubuntu

### ISSUE THREAD

**Issue by earlin** [ologon/Sprytile#3] opened 2020-02-10 00:09 UTC
![image](https://user-images.githubusercontent.com/47703302/74113037-db57be80-4ba1-11ea-98f3-2210c507ac49.png)

Thanks for your efforts by the way !

**Comment by ologon** [comment] 2020-02-10 00:59
Hi!

I don’t use Ubuntu so I can’t check myself, but numpy normally comes bundled with blender, so probably the cause is in the python blender is using.

You can try a few things:
- Use the official linux blender zip file from blender.org
- Check what python blender is using by using “print(sys.path)” in the blender scripting window, and make sure numpy is there. If not, you may have to manually install it

**Comment by WebOptimusPrime** [comment] 2020-02-11 16:16
Maybe it is just my shitty ubuntu installation, I'm a linux novice, it's been a month, I fucked up my apt registry Hhhhh, I can not install software without it being broken.

**Comment by ologon** [comment] 2020-02-13 02:12
Searching for "blender ubuntu numpy not found" gave some results. Looks like installing blender with the following might also work:

```
sudo apt-get install snapd 
sudo snap install blender --classic
```

If it doesn't help, this is worth a try:

```
sudo apt-get install python-pip  
sudo pip install numpy
```

Since it is not a problem with sprytile itself, I'll close this issue for now. Let me know in the comments if you need further info!

**Closed** 2020-02-13 02:13 UTC
Labels: question
