### ISSUE TITLE
unable to enable addon

### ISSUE THREAD

**Issue by luntik2012** [ologon/Sprytile#12] opened 2020-05-31 06:35 UTC
![image](https://user-images.githubusercontent.com/8270543/83346060-0ec18300-a322-11ea-990b-6439eeb70562.png)

**Comment by ologon** [comment] 2020-06-01 02:31
Please make sure sprytile was installed correctly. First uninstall the current version and make sure  there's no trace of it in C:\Users\spadafina_alfredo\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons. Restart blender, then install again the latest version of sprytile (beta9)

**Comment by vulture-boy** [comment] 2020-06-03 19:22
I've had this issue too. It happens when another instance of sprytile was installed on blender. Uninstall, restart blender, install and it should work!

**Comment by ologon** [comment] 2020-06-06 07:20
I am closing this issue as unable to reproduce. If you need further help, please leave a comment!

**Closed by ologon** 2020-06-06 07:20 UTC
Labels: question
